export const IPC_CHANNELS = {
  systemGetRuntimeInfo: "system:get-runtime-info",
  systemListExternalApplications:
    "system:list-external-applications",
  systemOpenExternalApplication:
    "system:open-external-application",
  systemListExternalTerminals: "system:list-external-terminals",
  systemOpenExternalTerminal: "system:open-external-terminal",
  systemOpenDirectory: "system:open-directory",
  systemOpenFileLocation: "system:open-file-location",
  accountList: "account:list",
  accountSave: "account:save",
  accountBind: "account:bind",
  accountUnbind: "account:unbind",
  accountGetRemovalImpact: "account:get-removal-impact",
  accountRemove: "account:remove",
  accountTest: "account:test",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  settingsClearAiApiKey: "settings:clear-ai-api-key",
  aiTestConnection: "ai:test-connection",
  aiGenerateCommitMessage: "ai:generate-commit-message",
  codeAnalysisGetState: "code-analysis:get-state",
  codeAnalysisStart: "code-analysis:start",
  codeAnalysisCancel: "code-analysis:cancel",
  codeAnalysisGetSnapshot: "code-analysis:get-snapshot",
  codeAnalysisReadFile: "code-analysis:read-file",
  codeAnalysisInstallLanguageServer:
    "code-analysis:install-language-server",
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowClose: "window:close",
  windowOpenDiffViewer: "window:open-diff-viewer",
  gitGetEnvironment: "git:get-environment",
  gitInspectRepository: "git:inspect-repository",
  workspaceGetCurrent: "workspace:get-current",
  workspaceGetState: "workspace:get-state",
  workspaceCreate: "workspace:create",
  workspaceSwitch: "workspace:switch",
  workspaceRename: "workspace:rename",
  workspaceDelete: "workspace:delete",
  workspaceSelectDirectory: "workspace:select-directory",
  workspaceAddEntry: "workspace:add-entry",
  workspaceRescan: "workspace:rescan",
  workspaceUpdateEntry: "workspace:update-entry",
  workspaceRemoveEntry: "workspace:remove-entry",
  workspaceSetGroupCollapsed: "workspace:set-group-collapsed",
  workspaceSelectEntry: "workspace:select-entry",
  workspaceSelectTarget: "workspace:select-target",
  workspaceRefresh: "workspace:refresh",
  repositoryGetChanges: "repository:get-changes",
  repositoryGetDiff: "repository:get-diff",
  repositoryGetHistory: "repository:get-history",
  repositoryGetCommit: "repository:get-commit",
  repositoryGetCommitDiff: "repository:get-commit-diff",
  repositoryGetStashes: "repository:get-stashes",
  repositoryGetStashFiles: "repository:get-stash-files",
  repositoryGetStashDiff: "repository:get-stash-diff",
  repositoryGetBranches: "repository:get-branches",
  repositoryCancelQuery: "repository:cancel-query",
  repositoryStage: "repository:stage",
  repositoryUnstage: "repository:unstage",
  repositoryDiscard: "repository:discard",
  repositoryMutateStash: "repository:mutate-stash",
  repositoryCreateCommit: "repository:create-commit",
  repositoryCommandPreflight: "repository:command-preflight",
  repositoryCommandExecute: "repository:command-execute",
  repositoryCancelOperation: "repository:cancel-operation",
  worktreeSelectDirectory: "worktree:select-directory",
  worktreeCommandPreflight: "worktree:command-preflight",
  worktreeCommandExecute: "worktree:command-execute"
} as const;

export const IPC_EVENTS = {
  settingsChanged: "settings:changed",
  workspaceStateChanged: "workspace:state-changed",
  codeAnalysisStateChanged: "code-analysis:state-changed"
} as const;
