export const IPC_CHANNELS = {
  systemGetRuntimeInfo: "system:get-runtime-info",
  systemListExternalTerminals: "system:list-external-terminals",
  systemOpenExternalTerminal: "system:open-external-terminal",
  accountList: "account:list",
  accountSave: "account:save",
  accountBind: "account:bind",
  accountUnbind: "account:unbind",
  accountGetRemovalImpact: "account:get-removal-impact",
  accountRemove: "account:remove",
  accountTest: "account:test",
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowClose: "window:close",
  gitGetEnvironment: "git:get-environment",
  gitInspectRepository: "git:inspect-repository",
  workspaceGetCurrent: "workspace:get-current",
  workspaceGetState: "workspace:get-state",
  workspaceSelectDirectory: "workspace:select-directory",
  workspaceAddEntry: "workspace:add-entry",
  workspaceRescan: "workspace:rescan",
  workspaceUpdateEntry: "workspace:update-entry",
  workspaceSetGroupCollapsed: "workspace:set-group-collapsed",
  workspaceSelectEntry: "workspace:select-entry",
  workspaceSelectTarget: "workspace:select-target",
  workspaceRefresh: "workspace:refresh",
  repositoryGetChanges: "repository:get-changes",
  repositoryGetDiff: "repository:get-diff",
  repositoryGetHistory: "repository:get-history",
  repositoryGetCommit: "repository:get-commit",
  repositoryGetBranches: "repository:get-branches",
  repositoryCancelQuery: "repository:cancel-query",
  repositoryStage: "repository:stage",
  repositoryUnstage: "repository:unstage",
  repositoryCreateCommit: "repository:create-commit",
  repositoryCommandPreflight: "repository:command-preflight",
  repositoryCommandExecute: "repository:command-execute",
  repositoryCancelOperation: "repository:cancel-operation",
  worktreeSelectDirectory: "worktree:select-directory",
  worktreeCommandPreflight: "worktree:command-preflight",
  worktreeCommandExecute: "worktree:command-execute"
} as const;

export const IPC_EVENTS = {
  workspaceStateChanged: "workspace:state-changed"
} as const;
